controller_list:
  - name: fake_ur5_arm_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      - ur5_finger_joint1
initial:  # Define initial robot poses.
  - group: ur5_arm
    pose: allZeros