// Generated by gencpp from file mir_actions/MirMoveBaseFeedback.msg
// DO NOT EDIT!


#ifndef MIR_ACTIONS_MESSAGE_MIRMOVEBASEFEEDBACK_H
#define MIR_ACTIONS_MESSAGE_MIRMOVEBASEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace mir_actions
{
template <class ContainerAllocator>
struct MirMoveBaseFeedback_
{
  typedef MirMoveBaseFeedback_<ContainerAllocator> Type;

  MirMoveBaseFeedback_()
    : state(0)
    , base_position()  {
    }
  MirMoveBaseFeedback_(const ContainerAllocator& _alloc)
    : state(0)
    , base_position(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _state_type;
  _state_type state;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _base_position_type;
  _base_position_type base_position;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(PLANNING)
  #undef PLANNING
#endif
#if defined(_WIN32) && defined(CONTROLLING)
  #undef CONTROLLING
#endif
#if defined(_WIN32) && defined(CLEARING)
  #undef CLEARING
#endif

  enum {
    PLANNING = 0,
    CONTROLLING = 1,
    CLEARING = 2,
  };


  typedef boost::shared_ptr< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MirMoveBaseFeedback_

typedef ::mir_actions::MirMoveBaseFeedback_<std::allocator<void> > MirMoveBaseFeedback;

typedef boost::shared_ptr< ::mir_actions::MirMoveBaseFeedback > MirMoveBaseFeedbackPtr;
typedef boost::shared_ptr< ::mir_actions::MirMoveBaseFeedback const> MirMoveBaseFeedbackConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator1> & lhs, const ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.base_position == rhs.base_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator1> & lhs, const ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mir_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "444e2bb5720367d489f77ad420c36753";
  }

  static const char* value(const ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x444e2bb5720367d4ULL;
  static const uint64_t static_value2 = 0x89f77ad420c36753ULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_actions/MirMoveBaseFeedback";
  }

  static const char* value(const ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int8 PLANNING = 0\n"
"int8 CONTROLLING = 1\n"
"int8 CLEARING = 2\n"
"int8 state\n"
"geometry_msgs/PoseStamped base_position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.base_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MirMoveBaseFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_actions::MirMoveBaseFeedback_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "base_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.base_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_ACTIONS_MESSAGE_MIRMOVEBASEFEEDBACK_H
